version: '3.8'

networks:
  inception:
    name: "inception-network"
    driver: bridge
  
volumes:
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/paugusto/data/mariadb
  
  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/paugusto/data/wordpress

services:
  mariadb:
    image: mariadb:inception
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb-data:/var/lib/mysql
  
  nginx:
    image: nginx:inception
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - wordpress
  
  wordpress:
    image: wordpress:inception
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/html/wordpress
    depends_on:
      - mariadb