version: '3.5'

networks:
  inception-network:
    driver: bridge

services:
  nginx: 
    container_name: nginx
    build: ./nginx
    ports:
      - 443:443
    restart: always
    networks:
      - inception-network  