version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    build: 
      context: ./requirements/mariadb
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
  
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress-data:/var/www/html/wordpress
    depends_on:
      - wordpress
  
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress-data:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
  
volumes:
  mariadb-data:
    driver_opts:
      o: bind
      type: none
      device: /home/paugusto/data/mariadb
  wordpress-data:
    driver_opts:
      o: bind
      type: none
      device: /home/paugusto/data/wordpress

networks:
  inception:
    name: "inception-network"
    driver: bridge